# Generated by Django 4.2.3 on 2023-07-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsello_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='date',
        ),
        migrations.AddField(
            model_name='artwork',
            name='year',
            field=models.PositiveIntegerField(default=2023),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
