# Generated by Django 4.2.3 on 2023-07-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsello_api', '0003_artwork_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_order_id', models.CharField(max_length=75)),
                ('created', models.CharField(max_length=75)),
                ('customer_paypal_id', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=75)),
                ('customer_name', models.CharField(max_length=50)),
                ('order_amount', models.PositiveIntegerField()),
                ('payment_id', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=25)),
                ('payment_protection', models.CharField(max_length=25)),
                ('reference_id', models.CharField(max_length=50)),
                ('shipping_street_address', models.CharField(max_length=75)),
                ('shipping_city', models.CharField(max_length=25)),
                ('shipping_state', models.CharField(max_length=10)),
                ('shipping_country_code', models.CharField(max_length=10)),
                ('shipping_zipcode', models.CharField(max_length=25)),
                ('order_status', models.CharField(max_length=25)),
                ('ordered_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_art', to='carsello_api.artwork')),
            ],
        ),
    ]
