# Generated by Django 4.2.3 on 2023-07-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsello_api', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
