# Generated by Django 4.2.3 on 2023-08-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsello_api', '0005_artwork_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='dimensions',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
