# Generated by Django 4.2.3 on 2023-08-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsello_api', '0006_artwork_dimensions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='image',
            new_name='primary_image',
        ),
    ]
