# Generated by Django 4.2.3 on 2023-08-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsello_api', '0007_rename_image_artwork_primary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='support_images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
