# Generated by Django 4.2.3 on 2023-08-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsello_api', '0008_artwork_support_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='support_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
