# Generated by Django 4.2.3 on 2023-08-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsello_api', '0009_alter_artwork_support_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='sold',
        ),
    ]
