# Generated by Django 4.2.3 on 2023-08-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsello_api', '0013_alter_event_details_alter_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='sort_index',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
