# Generated by Django 4.2.3 on 2023-08-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsello_api', '0014_artwork_sort_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='sort_index',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
