# Generated by Django 4.2.3 on 2023-08-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsello_api', '0015_alter_artwork_sort_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'permissions': (('quantity_decrement', 'can decrease quantity of product after purchase'),)},
        ),
    ]
