# Generated by Django 4.2.3 on 2023-09-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsello_api', '0017_order_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='range',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
